### ISSUE TITLE
Ability to use existing VPC and Security Group?

### ISSUE THREAD

**Issue by dimitry** [honerlaw/serverless-fargate-plugin#13]
Not all of our cloud infrastructure is controlled by Serverless.

Serverless allows to use existing VPC at Provider config level by passing existing subnetIds and securityGroupIds. Is it possible to do the same with this Fargate plugin?

Thanks

**Comment by dimitry** [comment]
Never mind, should have just looked at the code. Apologies.

(For reference: https://github.com/honerlaw/serverless-fargate-plugin/blob/master/src/resources/vpc.ts has a method of `useExistingVPC()`. Look there to figure out how to pass existing VPC and security group configuration)

**Comment by kevlarr** [comment]
Thanks @dimitry, had same issue and that would have taken me a bit to find.
